### ISSUE TITLE
Enhancement: Add AltGr (Alt Graph) Key 

### ISSUE THREAD

**Issue by forrest96er** [CharaChorder/CCOS-firmware#38]
In order to improve the support of other keyboard layouts (like German ) there should be added support for AltGr ( Alt Graph) Key. 
Actual if you want to use the German Layout, you can not write some symbols like: ² ³ { [ ] } @ € ~ |µ. 

On the keyboard with AltGr  the Right_Alt Key gets replaced with AltGr. 

On GitHub the is another Issue that is also related to this problem. 
[https://github.com/CharaChorder/CCOS-firmware/issues/17] (https://github.com/CharaChorder/CCOS-firmware/issues/17)

However the is also described some problems with German "Umlaute" like ö ä ü ...  .  

On my CaraChorder One I can write "Umlaute" with US layout on CC and German system Layout without any problems.  

For writing German Chords I would have to change the keyboard layout on CC and add some German words. So, writing chords in German is actually not tested by myself.

**Comment by Theaninova** [comment]
This is already possible by assigning right alt and purely dependent on your OS-layout. This will be addressed in soon https://github.com/CharaChorder/DeviceManager/issues/11
