### ISSUE TITLE
Defect: turning off arpeggiates doesn't disable colon from being treated as an arpeggiate

### ISSUE THREAD

**Issue by jdestgermain** [CharaChorder/CCOS-firmware#69]
**Describe the bug**

**To Reproduce**
1. Turn off arpeggiates
2. Chord a word
3. Type colon immediately after (within the arpeggiate window)
4. 

**Expected behavior**
It should not be treated arpeggiately, but it is

**Please complete the following information:**
 - OS: Windows
 - CharaChorder Device: CharaChorder one
 - CCOS Version: 1.9.x alpha, but others report it as well

**Comment by Theaninova** [comment]
> Actually I don't think this is a bug related to arpeggiates, but rather that shift+; might be a built in chord?

100% that's what's going on. in behaves like a chord, aka subject to chord tolerances and auto-delete behaviour.
